server:
  port: ${CONFIG_PORT:8888}

spring:
  application:
    name: ms-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config/
        bootstrap: true
      enabled: true